[options]
SigLevel = Optional TrustAll
CacheDir = /var/cache/pacman/pkg/
CleanMethod = KeepInstalled
Architecture = auto

[hiroki-local]
SigLevel = Optional TrustAll
Server = file:///usr/share/hiroki/cache

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
