# Hiroki OS - mkinitcpio
MODULES=(btrfs ext4)
BINARIES=()
FILES=()
HOOKS=(base udev modconf kms keyboard keymap consolefont block filesystems fsck archiso archiso_loop_mnt archiso_pxe_common)
COMPRESSION="zstd"
